Ce script sert à la comparaison des modeles de random forest et des sélections de variables.

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
path = r"C:\Users\ahmed\MFE project"
df = pd.read_csv([os.path.join(path, i) for i in os.listdir(path) if i.find("résultats_final_info_kfold.csv")>-1][0])

In [3]:
df

,Unnamed: 0,annee,type,date,num,classe,num2,num3,ordre,pred_all,pred_amplicon,pred_tsv,pred_Pearson,pred_Spearman,pred_rfe,pred_rf,fold,ordre1
0,0,2018,NDN,4-12-18,1,OPT,7,83,0,OPT,OPT,OPT,OPT,OPT,OPT,OPT,2,0
1,1,2018,NDN,4-12-18,1,OPT,8,83,1,OPT,OPT,SOPT,OPT,OPT,OPT,OPT,1,1
2,2,2018,NDN,4-12-18,1,SOPT,5,83,2,SOPT,SOPT,SOPT,SOPT,SOPT,SOPT,SOPT,0,2
3,3,2019,CVC,02-04-19,1,NC,83,137,3,NC,NC,NC,NC,NC,NC,NC,3,3
4,4,2019,CVC,02-04-19,1,NVA,75,137,4,NVA,NVA,NVA,NVA,NVA,NVA,NVA,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,593,2021,OBL,23-03-21,2,OPT,11,636,593,OPT,OPT,OPT,OPT,OPT,OPT,OPT,1,593
594,594,2021,OBL,23-03-21,2,OPT,12,636,594,OPT,OPT,OPT,OPT,OPT,OPT,OPT,1,594
595,595,2021,OBL,23-03-21,2,OPT,13,636,595,OPT,NVA,OPT,OPT,OPT,OPT,OPT,0,595
596,596,2021,OBL,23-03-21,2,SOPT,47,636,596,SOPT,SOPT,OPT,SOPT,SOPT,SOPT,SOPT,3,596
597,597,2021,OBL,23-03-21,2,SOPT,48,636,597,OPT,SOPT,OPT,OPT,OPT,OPT,OPT,1,597

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true=df["classe"], y_pred= df["pred_rfe"])

0.9364548494983278

In [24]:
from statsmodels.stats.contingency_tables import mcnemar

def macnemar(preda, predb, classe):
    Ta = preda==classe
    Tb = predb==classe

    a = ((Ta==True)*(Tb==True)).sum()
    b = ((Ta==True)*(Tb==False)).sum()
    c = ((Ta==False)*(Tb==True)).sum()
    d = ((Ta==False)*(Tb==False)).sum()

    ct = [[a,b], [c,d]]

    m = mcnemar(ct, exact=True)
    print(m, (b+c))

In [41]:
macnemar(df["pred_all"], df["pred_rfe"], df["classe"])

pvalue      0.057373046875
statistic   3.0 14